name: Beta Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    name: CI and Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v3
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report tool versions
      run: rojo --version

    - name: Deploy
      run: rojo upload --cookie "$ROBLOSECURITY" --asset_id 6605037523 default.project.json
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}